// Categorias centralizadas para todos os cadastros do sistema

export const CategoriaAcessoriosCabeca = [
  { value: 'chapeu', label: 'Chapéu' },
  { value: 'tiara', label: 'Tiara' },
  { value: 'bone', label: 'Boné' },
  { value: 'lenco', label: 'Lenço' },
  { value: 'gorro', label: 'Gorro' },
  { value: 'turbante', label: 'Turbante' },
  { value: 'bandana', label: 'Bandana' },
  { value: 'faixa', label: 'Faixa' },
  { value: 'outro_acessorios_cabeca', label: 'Outro (Acessórios de Cabeça)' },
];

export const CategoriaTops = [
  { value: 'camiseta', label: 'Camiseta' },
  { value: 'camisa', label: 'Camisa' },
  { value: 'blusa', label: 'Blusa' },
  { value: 'jaqueta', label: 'Jaqueta' },
  { value: 'casaco', label: 'Casaco' },
  { value: 'sueter', label: 'Suéter' },
  { value: 'regata', label: 'Regata' },
  { value: 'colete', label: 'Colete' },
  { value: 'polo', label: 'Polo' },
  { value: 'tank-top', label: 'Tank Top' },
  { value: 'cardigan', label: 'Cardigan' },
  { value: 'tunica', label: 'Túnica' },
  { value: 'top', label: 'Top' },
  { value: 'blazer', label: 'Blazer' },
  { value: 'trench-coat', label: 'Trench Coat' },
  { value: 'parka', label: 'Parka' },
  { value: 'blusao', label: 'Blusão' },
  { value: 'moletom', label: 'Moletom' },
  { value: 'hoodie', label: 'Hoodie' },
  // Macacões movidos para Tops
  { value: 'macacao', label: 'Macacão' },
  { value: 'jardineira', label: 'Jardineira' },
  { value: 'overalls', label: 'Overalls' },
  { value: 'macaquinho', label: 'Macaquinho' },
  // Vestidos movidos para Tops
  { value: 'vestido', label: 'Vestido' },
  { value: 'vestido-longo', label: 'Vestido Longo' },
  { value: 'vestido-curto', label: 'Vestido Curto' },
  { value: 'vestido-midi', label: 'Vestido Midi' },
  { value: 'vestido-tubo', label: 'Vestido Tubo' },
  { value: 'vestido-a-line', label: 'Vestido A-Line' },
  { value: 'vestido-sheath', label: 'Vestido Sheath' },
  { value: 'vestido-wrap', label: 'Vestido Wrap' },
  { value: 'vestido-maxi', label: 'Vestido Maxi' },
  { value: 'vestido-mini', label: 'Vestido Mini' },
  { value: 'vestido-boho', label: 'Vestido Boho' },
  { value: 'outro_tops', label: 'Outro (Tops)' },
];

export const CategoriaCalcasSaias = [
  { value: 'calca', label: 'Calça' },
  { value: 'saia', label: 'Saia' },
  { value: 'short', label: 'Shorts' },
  { value: 'legging', label: 'Legging' },
  { value: 'bermuda', label: 'Bermuda' },
  { value: 'calca-cargo', label: 'Calça Cargo' },
  { value: 'calca-skinny', label: 'Calça Skinny' },
  { value: 'calca-flare', label: 'Calça Flare' },
  { value: 'calca-wide-leg', label: 'Calça Wide Leg' },
  { value: 'calca-palazzo', label: 'Calça Palazzo' },
  { value: 'saia-midi', label: 'Saia Midi' },
  { value: 'saia-longa', label: 'Saia Longa' },
  { value: 'saia-mini', label: 'Saia Mini' },
  { value: 'saia-plissada', label: 'Saia Plissada' },
  { value: 'saia-tubo', label: 'Saia Tubo' },
  { value: 'saia-gode', label: 'Saia Godê' },
  { value: 'outro_calcas_saias', label: 'Outro (Calças e Saias)' },
];

export const CategoriaCalcados = [
  { value: 'tenis', label: 'Tênis' },
  { value: 'sandalia', label: 'Sandália' },
  { value: 'bota', label: 'Bota' },
  { value: 'sapato', label: 'Sapato' },
  { value: 'chinelo', label: 'Chinelo' },
  { value: 'sapatilha', label: 'Sapatilha' },
  { value: 'mocassim', label: 'Mocassim' },
  { value: 'oxford', label: 'Oxford' },
  { value: 'derby', label: 'Derby' },
  { value: 'ankle-boot', label: 'Ankle Boot' },
  { value: 'chelsea-boot', label: 'Chelsea Boot' },
  { value: 'sneaker', label: 'Sneaker' },
  { value: 'slip-on', label: 'Slip-on' },
  { value: 'loafer', label: 'Loafer' },
  { value: 'outro_calcados', label: 'Outro (Calçados)' },
];

export const CategoriaAcessorios = [
  { value: 'cinto', label: 'Cinto' },
  { value: 'oculos', label: 'Óculos' },
  { value: 'bolsa', label: 'Bolsa' },
  { value: 'relogio', label: 'Relógio' },
  { value: 'brinco', label: 'Brinco' },
  { value: 'colar', label: 'Colar' },
  { value: 'pulseira', label: 'Pulseira' },
  { value: 'anel', label: 'Anel' },
  { value: 'carteira', label: 'Carteira' },
  { value: 'mochila', label: 'Mochila' },
  { value: 'pasta', label: 'Pasta' },
  { value: 'necessaire', label: 'Necessaire' },
  { value: 'outro_acessorios', label: 'Outro (Acessórios)' },
];

// Para uso em selects, pode-se fazer Object.values(CategoriaTops) etc. 